services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: springboot
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    networks:
      - campus
networks:
  campus:
    driver: bridge
