package placement.college.management;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Data // Lombok annotation for getters, setters, equals, hashcode, and toString methods
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Table(name = "students") 
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generate unique IDs
    private Long id; // Primary key for the student entity

    @Column(nullable = false) // Ensures that the name cannot be null in the database
    @NotBlank(message = "Name is required")
    private String name;

    @Column(nullable = false) // Ensures that department cannot be null
    @NotBlank(message = "Department is required")
    private String department;

    @Column(nullable = false)
    @Min(value = 1, message = "Year must be at least 1")
    @Max(value = 4, message = "Year cannot be more than 4")
    private int year;

    @Column(nullable = false, unique = true) 
    @Email(message = "Email should be valid")
    @NotBlank(message = "Email is required")
    private String email;

    @Column(nullable = false, unique = true) // Ensure phone number is unique
    @Pattern(regexp = "\\d{10}", message = "Phone number must be 10 digits")
    @NotBlank(message = "Phone number is required")
    private String phone;
    
    public Long getId() {
        return id;

    }
    
    public void setId(Long id) {
        this.id = id;

    }

}

    // Getters and Setters (Generated by Lombok's @Data annotation)