export const AppliedData=[
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Muntaha",
    "branch": "Mechanical Engineering",
    "cgpa": 7.2,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 7.5,
    "date": "2025-03-10",
    "degree": "B.Tech",
    "diploma": 82,
    "gap": 0,
    "id": 2,
    "tenth": 78,
    "twelfth": 72,
    "year": "2025"
  },
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Fareed",
    "branch": "Electrical Engineering",
    "cgpa": 7.8,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 8.0,
    "date": "2025-06-22",
    "degree": "B.Tech",
    "diploma": 84,
    "gap": 0,
    "id": 3,
    "tenth": 85,
    "twelfth": 77,
    "year": "2025"
  },
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Afraa",
    "branch": "Information Technology",
    "cgpa": 8.1,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 9.0,
    "date": "2025-09-05",
    "degree": "B.Tech",
    "diploma": 87,
    "gap": 0,
    "id": 4,
    "tenth": 82,
    "twelfth": 79,
    "year": "2025"
  },
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Jhon Doe",
    "branch": "Civil Engineering",
    "cgpa": 7.5,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 7.8,
    "date": "2025-11-15",
    "degree": "B.Tech",
    "diploma": 80,
    "gap": 0,
    "id": 5,
    "tenth": 76,
    "twelfth": 74,
    "year": "2025"
  },
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Steven Thompson",
    "branch": "Electronics & Communication",
    "cgpa": 8.2,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 8.7,
    "date": "2025-02-28",
    "degree": "B.Tech",
    "diploma": 88,
    "gap": 0,
    "id": 6,
    "tenth": 89,
    "twelfth": 81,
    "year": "2025"
  },
  {
    "activeBacklog": 0,
    "backlog": 0,
    "name":"Eddie Gurero",
    "branch": "Chemical Engineering",
    "cgpa": 7.4,
    "companies": [],
    "criteria": "Minimum CGPA 7.0, No Active Backlogs",
    "ctc": 8.2,
    "date": "2025-08-12",
    "degree": "B.Tech",
    "diploma": 83,
    "gap": 0,
    "id": 7,
    "tenth": 79,
    "twelfth": 76,
    "year": "2025"
  }
]